### ISSUE TITLE
git grep *ack* result buffer fails to parse filenames with the pattern hypen numbers hyphen, like abc-123-def.txt

### ISSUE THREAD

**Issue by jaknel** [leoliu/ack-el#13]
\*ack\* result buffer parses the numbers in a filename as the line number, breaking `compile-goto-error`

Using RET to visit a broken file results in a prompt "Find this ack match in" with a directory prompt, trying to find the partial match up until the filename's first hyphen.

abc-123-def.txt fails
abc-123.txt works

**Comment by joaotavora** [comment]
Thanks for the report. I think I saw this happen once or twice myself.  I don't have time to fix it right now, but I suspect the problem to be in Emacs's `compilation-mode`. At least partly.

**Comment by jaknel** [comment]
#14 fixes the issue for me by not matching on hyphens. I don't know what format the hyphen was meant to match
