### ISSUE TITLE
How can I bind a different keybinding for C-u M-x ack?

### ISSUE THREAD

**Issue by dubiousdavid** [leoliu/ack-el#5]
What is the actual command that gets called?

**Comment by dubiousdavid** [comment]
I ended up writing this function if this is helpful to anyone:
```elisp
(defun ack-from-root ()
  (interactive)
  (let ((current-prefix-arg 4)) ;; emulate C-u
    (call-interactively 'ack)))
```

**Comment by leoliu** [comment]
hi @dubiousdavid,

The default function to find a suitable directory to search is customisable via `ack-default-directory-function` i.e. you can define your own preference by providing such a function:

```
(defun my-ack-default-directory (_arg)
  (or (ack-guess-project-root default-directory)
      (read-directory-name "In directory: " nil nil t)))
```

The above would guess a project root and use it, failing that ask the user for a directory. Does this help?

Leo

**Comment by dubiousdavid** [comment]
I couldn't get the above to work.

**Comment by leoliu** [comment]
Did you then `(setq ack-default-directory-function #'my-ack-default-directory)`?

**Comment by joaotavora** [comment]
Closing, as I don't know if the above discussion is still up to date.  @dubiousdavid maybe you can try the latest version and tell me if you still have the problem.
