### ISSUE TITLE
Ability to choose underlining search program

### ISSUE THREAD

**Issue by dubiousdavid** [leoliu/ack-el#6]
I'd like to be able to specify `ag` over `ack` by calling a function provided by ack-el. Currently I have both `ag` and `ack` installed on my system. `ack` is used simply because the order in the code dictates that.

**Comment by leoliu** [comment]
hi @dubiousdavid，

You need to customise `ack-command` for example by putting `(setq ack-command "ag ")` in your emacs init file.

**Comment by dubiousdavid** [comment]
That worked. Thanks!
