### ISSUE TITLE
M-Y in minibuffer says "Previous command was not a yank"

### ISSUE THREAD

**Issue by fleutot** [leoliu/ack-el#7]
M-x ack RET
M-Y

expected: yank the symbol at point in the buffer from which I called ack
actual: "Previous command was not a yank"

Installed as per the readme with M-x package-install RET ack RET. 
v0.9.
GNU Emacs 24.5.1

Did I miss something?

**Comment by leoliu** [comment]
`M-Y` might not work if you are running emacs in terminal. In such case `M-Y` is treated as `M-y`. Is this the case for you?

**Comment by fleutot** [comment]
No, sorry, emacs is in its own window.

**Comment by leoliu** [comment]
Does other keys such as `M-I` or `M-G` in `ack-minibuffer-local-map` work for you? Are you able to reproduce the issue starting from `Emacs -Q`? Which OS are you running Emacs in? I can't reproduce this issue here on OSX.

**Comment by fleutot** [comment]
Ubuntu 15.10 here.

I tried with `-Q`, only ran `(package-initialize)` and `(require 'ack)`. None of `M-I`, `M-G`, or `M-Y` seems to work.

The first result in the minibuffer is: "Symbol not found".

**Comment by leoliu** [comment]
Hi @fleutot 

That seems very strange i.e. seems to suggest something else is wrong with emacs.

Could you upgrade to latest `ack.el` and try again? Instead of pressing `Meta + Shifit + Y` try also `ESC + Shift + Y`. Thanks.

**Comment by fleutot** [comment]
Wait. A. Minute. I never tried `Meta + Shift + Y`. But it works! I don't understand, both the documentation and the code use `M-Y`, where does the `Shift` come from?

**Comment by leoliu** [comment]
@fleutot no worries. I am glad we sorted it out.
