### ISSUE TITLE
Search for symbol at point

### ISSUE THREAD

**Issue by dubiousdavid** [leoliu/ack-el#8]
It would be great to have a function that will automatically invoke a search using the symbol at point. Currently this requires three steps: invoke ack, keystroke to copy symbol at point to minibuffer, and hit enter.

**Comment by joaotavora** [comment]
Here's how I do it:

```(add-hook 'ack-minibuffer-setup-hook 'ack-yank-symbol-at-point t)```

If you lobby strongly enough, we could make this the default, but I think adding a function to a hook is equally clean.

**Comment by joaotavora** [comment]
This has actually been the default since a while, though some people prefer otherwise (#12)
